"""Tests for automatic family selection and cross-validation.

The core claim is a recovery claim: given data generated by a known family,
selection should name that family. That is checked across families with very
different tail behaviour, since the failure mode worth catching is a criterion
that quietly prefers whichever family has the most parameters.

The rest guards the contract around it -- bivariate-only families dropping out
in higher dimensions, a family that fails to converge being *reported* rather
than raised, and the ranking column actually driving the sort order.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

import rcopula as rc
from rcopula.select import FAMILIES, cross_validate, select_copula


class TestFamilyRecovery:
    @pytest.mark.parametrize(
        ("copula", "expected"),
        [
            (rc.ClaytonCopula(3.0), "clayton"),
            (rc.GumbelCopula(2.5), "gumbel"),
            (rc.FrankCopula(6.0), "frank"),
            (rc.JoeCopula(3.0), "joe"),
            (rc.AMHCopula(0.9), "amh"),
        ],
    )
    def test_recovers_the_generating_family(self, copula: rc.Copula, expected: str) -> None:
        u = copula.rvs(1500, random_state=0)
        assert select_copula(u, families="archimedean").best_name == expected

    def test_recovers_gaussian_among_elliptical_and_archimedean(self) -> None:
        u = rc.GaussianCopula(0.7).rvs(2000, random_state=0)
        ranking = select_copula(u, families=["gaussian", "clayton", "gumbel", "frank"])
        assert ranking.best_name == "gaussian"

    def test_recovers_student_when_both_tails_are_dependent(self) -> None:
        """The case that matters: t beats Gaussian only if the tails demand it."""
        u = rc.StudentCopula(0.7, df=3.0).rvs(2000, random_state=1)
        ranking = select_copula(u, families=["gaussian", "student", "frank", "gumbel"])
        assert ranking.best_name == "student"

    def test_does_not_prefer_student_when_gaussian_suffices(self) -> None:
        """The complexity penalty has to bite, or every ranking is meaningless."""
        u = rc.GaussianCopula(0.6).rvs(3000, random_state=2)
        ranking = select_copula(u, families=["gaussian", "student"])
        assert ranking.best_name == "gaussian"

    def test_independence_wins_on_independent_data(self) -> None:
        u = rc.IndependenceCopula(2).rvs(2000, random_state=3)
        ranking = select_copula(u, families=["independence", "gaussian", "frank", "clayton"])
        assert ranking.best_name == "independence"
        assert ranking.table.loc["independence", "n_params"] == 0
        assert ranking.table.loc["independence", "loglik"] == 0.0

    def test_the_winner_comes_back_fitted(self) -> None:
        u = rc.ClaytonCopula(3.0).rvs(1500, random_state=0)
        ranking = select_copula(u, families="archimedean")
        assert isinstance(ranking.best, rc.ClaytonCopula)
        assert ranking.best.theta == pytest.approx(3.0, abs=0.3)
        assert ranking.best_result.copula is ranking.best

    def test_the_table_explains_the_choice(self) -> None:
        """Tail dependence is reported next to the score, not left implicit."""
        u = rc.ClaytonCopula(4.0).rvs(1500, random_state=0)
        row = select_copula(u, families="archimedean").table.loc["clayton"]
        assert row["lambda_lower"] > 0.5
        assert row["lambda_upper"] == 0.0
        assert row["tau"] == pytest.approx(rc.cor_kendall(u)[0, 1], abs=0.05)


class TestDimensionHandling:
    def test_bivariate_only_families_drop_out(self) -> None:
        u = rc.GaussianCopula(0.5, dim=4).rvs(400, random_state=0)
        names = set(select_copula(u).table.index)
        assert not (names & {"galambos", "husler_reiss", "tawn", "tev", "plackett", "fgm"})
        assert {"gaussian", "clayton", "gumbel", "frank"} <= names

    def test_all_registered_families_appear_in_two_dimensions(self) -> None:
        u = rc.FrankCopula(4.0).rvs(400, random_state=0)
        assert set(select_copula(u).table.index) == set(FAMILIES)

    def test_asking_for_a_bivariate_family_in_higher_dimensions_is_an_error(self) -> None:
        u = rc.GaussianCopula(0.5, dim=3).rvs(200, random_state=0)
        with pytest.raises(ValueError, match="limited to dim <= 2"):
            select_copula(u, families=["plackett"])

    def test_a_group_with_no_admissible_member_is_an_error(self) -> None:
        u = rc.GaussianCopula(0.5, dim=5).rvs(200, random_state=0)
        with pytest.raises(ValueError, match="no family in group"):
            select_copula(u, families="other")


class TestFamilyArgument:
    def test_accepts_a_group_name(self) -> None:
        u = rc.ClaytonCopula(2.0).rvs(300, random_state=0)
        assert set(select_copula(u, families="elliptical").table.index) == {
            "gaussian",
            "student",
        }

    def test_accepts_explicit_names(self) -> None:
        u = rc.ClaytonCopula(2.0).rvs(300, random_state=0)
        table = select_copula(u, families=["clayton", "frank"]).table
        assert set(table.index) == {"clayton", "frank"}

    def test_accepts_copula_instances_for_full_control(self) -> None:
        """The escape hatch: a fixed df, which the registry cannot express."""
        u = rc.StudentCopula(0.7, df=3.0).rvs(800, random_state=0)
        ranking = select_copula(
            u,
            families=[
                rc.StudentCopula(0.5, df=3.0, df_fixed=True),
                rc.StudentCopula(0.5, df=30.0, df_fixed=True),
                rc.GaussianCopula(0.5),
            ],
        )
        assert ranking.table.loc["student", "n_params"] == 1
        assert ranking.best_name == "student"

    def test_duplicate_instance_names_are_disambiguated(self) -> None:
        u = rc.ClaytonCopula(2.0).rvs(300, random_state=0)
        table = select_copula(
            u,
            families=[
                rc.StudentCopula(0.5, df=3.0, df_fixed=True),
                rc.StudentCopula(0.5, df=20.0, df_fixed=True),
            ],
        ).table
        assert set(table.index) == {"student", "student_2"}

    def test_rejects_bad_arguments(self) -> None:
        u = rc.ClaytonCopula(2.0).rvs(200, random_state=0)
        with pytest.raises(ValueError, match="unknown family or group"):
            select_copula(u, families="parametric")
        with pytest.raises(ValueError, match="unknown family"):
            select_copula(u, families=["vine"])
        with pytest.raises(ValueError, match="families is empty"):
            select_copula(u, families=[])
        with pytest.raises(TypeError, match="group name"):
            select_copula(u, families=[1, 2])
        with pytest.raises(ValueError, match="dim=3"):
            select_copula(u, families=[rc.GaussianCopula(0.5, dim=3)])
        with pytest.raises(ValueError, match="criterion must be"):
            select_copula(u, criterion="dic")
        with pytest.raises(ValueError, match="gof must be"):
            select_copula(u, gof="jackknife")


class TestRanking:
    def test_the_criterion_drives_the_sort(self) -> None:
        u = rc.FrankCopula(5.0).rvs(600, random_state=0)
        for criterion in ("aic", "bic"):
            column = select_copula(u, families="archimedean", criterion=criterion).table[criterion]
            assert list(column) == sorted(column)

    def test_loglik_is_sorted_the_other_way(self) -> None:
        u = rc.FrankCopula(5.0).rvs(600, random_state=0)
        column = select_copula(u, families="archimedean", criterion="loglik").table["loglik"]
        assert list(column) == sorted(column, reverse=True)

    def test_bic_penalises_parameters_harder_than_aic(self) -> None:
        """Same fit, larger sample: BIC's penalty grows with log n, AIC's does not."""
        u = rc.StudentCopula(0.6, df=25.0).rvs(4000, random_state=0)
        names = ["gaussian", "student"]
        by_bic = select_copula(u, families=names, criterion="bic").table
        gap_aic = by_bic.loc["student", "aic"] - by_bic.loc["gaussian", "aic"]
        gap_bic = by_bic.loc["student", "bic"] - by_bic.loc["gaussian", "bic"]
        assert gap_bic > gap_aic

    def test_a_failing_family_is_reported_not_raised(self, monkeypatch) -> None:
        """A bad candidate must not abort the sweep, and must not vanish either."""
        import rcopula.select as select_module

        real_fit = select_module.fit

        def flaky(copula, u, **kwargs):
            if isinstance(copula, rc.GumbelCopula):
                raise RuntimeError("synthetic optimiser failure")
            return real_fit(copula, u, **kwargs)

        monkeypatch.setattr(select_module, "fit", flaky)
        u = rc.ClaytonCopula(2.0).rvs(400, random_state=0)
        table = select_copula(u, families=["clayton", "gumbel", "frank"]).table

        assert "gumbel" in table.index
        assert not table.loc["gumbel", "converged"]
        assert "synthetic optimiser failure" in str(table.loc["gumbel", "message"])
        assert np.isnan(table.loc["gumbel", "aic"])
        # Failures rank last whichever direction the criterion sorts.
        assert table.index[-1] == "gumbel"

    def test_summary_names_the_criterion_and_sample_size(self) -> None:
        u = rc.ClaytonCopula(2.0).rvs(500, random_state=0)
        text = select_copula(u, families="elliptical", criterion="bic").summary()
        assert "criterion = bic" in text
        assert "n = 500" in text
        assert (
            repr(select_copula(u, families="elliptical"))
            == select_copula(u, families="elliptical").summary()
        )

    def test_accepts_a_dataframe(self) -> None:
        u = rc.ClaytonCopula(2.0).rvs(400, random_state=0)
        frame = pd.DataFrame(u, columns=["a", "b"])
        assert select_copula(frame, families="archimedean").best_name == "clayton"

    def test_accepts_raw_unranked_data(self) -> None:
        """Selection rank-transforms, so margins are irrelevant -- as they must be."""
        u = rc.ClaytonCopula(3.0).rvs(1200, random_state=0)
        from scipy import stats

        raw = np.column_stack([stats.norm.ppf(u[:, 0]), stats.expon.ppf(u[:, 1])])
        assert (
            select_copula(raw, families="archimedean").best_name
            == select_copula(u, families="archimedean").best_name
        )


class TestCrossValidation:
    def test_the_right_family_scores_higher(self) -> None:
        u = rc.ClaytonCopula(3.0).rvs(800, random_state=0)
        right = cross_validate(rc.ClaytonCopula(), u, k=5, random_state=0)
        wrong = cross_validate(rc.GumbelCopula(), u, k=5, random_state=0)
        assert right > wrong

    def test_it_penalises_overfitting_where_loglik_cannot(self) -> None:
        """On Gaussian data the extra t parameter buys nothing out of sample."""
        u = rc.GaussianCopula(0.6).rvs(1500, random_state=4)
        gaussian = cross_validate(rc.GaussianCopula(), u, k=5, random_state=0)
        student = cross_validate(rc.StudentCopula(), u, k=5, random_state=0)
        in_sample = rc.fit(rc.StudentCopula(), u).loglik >= rc.fit(rc.GaussianCopula(), u).loglik
        assert in_sample  # the richer family always wins in sample ...
        assert gaussian > student  # ... and loses out of sample

    def test_is_on_a_full_sample_scale(self) -> None:
        """Comparable in magnitude to the in-sample log-likelihood, as R's xvCopula is."""
        u = rc.ClaytonCopula(3.0).rvs(800, random_state=0)
        xv = cross_validate(rc.ClaytonCopula(), u, k=10, random_state=0)
        full = rc.fit(rc.ClaytonCopula(), u).loglik
        assert 0.5 * full < xv < 1.5 * full

    def test_as_a_selection_criterion(self) -> None:
        u = rc.ClaytonCopula(3.0).rvs(800, random_state=0)
        ranking = select_copula(
            u, families=["clayton", "gumbel", "frank"], criterion="xv", k=5, random_state=0
        )
        assert ranking.best_name == "clayton"
        assert list(ranking.table["xv"]) == sorted(ranking.table["xv"], reverse=True)

    def test_rejects_an_impossible_fold_count(self) -> None:
        u = rc.ClaytonCopula(2.0).rvs(50, random_state=0)
        with pytest.raises(ValueError, match="k must be between"):
            cross_validate(rc.ClaytonCopula(), u, k=1)
        with pytest.raises(ValueError, match="k must be between"):
            cross_validate(rc.ClaytonCopula(), u, k=500)


class TestGoodnessOfFitColumn:
    def test_the_true_family_is_not_rejected_and_a_wrong_one_is(self) -> None:
        u = rc.ClaytonCopula(4.0).rvs(400, random_state=0)
        table = select_copula(
            u,
            families=["clayton", "gumbel"],
            gof="mult",
            n_rep=200,
            random_state=0,
        ).table
        assert table.loc["clayton", "gof_pvalue"] > 0.05
        assert table.loc["gumbel", "gof_pvalue"] < 0.05

    def test_true_enables_the_parametric_bootstrap(self) -> None:
        u = rc.FrankCopula(5.0).rvs(200, random_state=0)
        table = select_copula(u, families=["frank"], gof=True, n_rep=60, random_state=0).table
        assert 0.0 < table.loc["frank", "gof_pvalue"] < 1.0
        assert table.loc["frank", "gof_statistic"] > 0.0
